const ACTIONS = {
    //register constants
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',
    REGISTER: 'REGISTER',

    //login constans
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGIN: "LOGIN"
};

//main reducer action constants
export const MAIN_ACTIONS = {
    SHOW_ACTION_BAR: 'SHOW_ACTION_BAR',
    HIDE_ACTION_BAR: 'HIDE_ACTION_BAR',
    SELECT_BUCKET: 'SELECT_BUCKET',
    DESELECT_BUCKET: 'DESELECT_BUCKET',
    GET_BUCKETS: 'GET_BUCKETS',
    CREATE_BUCKET: 'CREATE_BUCKET',
    DELETE_BUCKET: 'DELETE_BUCKET',
    ENABLE_SELECTION_MODE: 'ENABLE_SELECTION_MODE',
    DISABLE_SELECTION_MODE: 'DISABLE_SELECTION_MODE',
    SINGLE_ITEM_ACTIONS_SELECTED: 'SINGLE_ITEM_ACTIONS_SELECTED'
};

export default ACTIONS;