export default EVENT_NAMES = {
    EVENT_BUCKETS_UPDATED = "EVENT_BUCKETS_UPDATED",    
    EVENT_BUCKET_CREATED = "EVENT_BUCKET_CREATED",
    EVENT_BUCKET_DELETED = "EVENT_BUCKET_DELETED",    

    EVENT_FILES_UPDATED = "EVENT_FILES_UPDATED",
    FILE_DELETED = "FILE_DELETED"
};