export default EVENT_NAMES = {
    EVENT_BUCKETS_UPDATED: "EVENT_BUCKETS_UPDATED",    
    EVENT_BUCKET_CREATED: "EVENT_BUCKET_CREATED",
    EVENT_BUCKET_DELETED: "EVENT_BUCKET_DELETED",    

    EVENT_FILES_UPDATED: "EVENT_FILES_UPDATED",
    EVENT_FILE_DELETED: "EVENT_FILE_DELETED",

    EVENT_FILE_DOWNLOAD_START: "EVENT_FILE_DOWNLOAD_START",
    EVENT_FILE_DOWNLOAD_PROGRESS: "EVENT_FILE_DOWNLOAD_PROGRESS",
    EVENT_FILE_DOWNLOAD_SUCCESS: "EVENT_FILE_DOWNLOAD_SUCCESS",
    EVENT_FILE_DOWNLOAD_ERROR: "EVENT_FILE_DOWNLOAD_ERROR",

    EVENT_FILE_UPLOAD_START: "EVENT_FILE_UPLOAD_START",
    EVENT_FILE_UPLOADED_PROGRESS: "EVENT_FILE_UPLOADED_PROGRESS",
    EVENT_FILE_UPLOADED_SUCCESSFULLY: "EVENT_FILE_UPLOADED_SUCCESSFULLY",
    EVENT_FILE_UPLOAD_ERROR: "EVENT_FILE_UPLOAD_ERROR",

    EVENT_SYNC_ENTRY_UPDATED: "EVENT_SYNC_ENTRY_UPDATED",
    EVENT_SYNC_STARTED: "EVENT_SYNC_STARTED"
};